apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  selector:
    matchLabels:
      app: client-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: client-deployment
    spec:
      containers:
        - name: client-deployment
          image: wnjenga/client_container:1.0.0
          ports:
            - containerPort: 3000