apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  selector:
    app: backend
  sessionAffinity: None