apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: wnjenga/yolo-backend:1.0.0
          ports:
            - containerPort: 5001
        - name: backend-database
          image: mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: MONGO_URL
          volumeMounts:
            - name: backend-volume
              mountPath: /data/db
      volumes:
        - name: backend-volume
          persistentVolumeClaim:
            claimName: mongodb-pvc