apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolok8s-backend-deployment
spec:
  selector:
    matchLabels:
      app: yolok8s-backend
  replicas : 2
  template:
    metadata:
      labels:
        app: yolok8s-backend
    spec:
      containers:
        - name: yolok8s-backend
          image: wnjenga/backend_container:1.0.0
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: yolok8s-backend-config
                  key: PORT
            - name: MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: yolok8s-backend-config
                  key: MONGODB_URI