apiVersion: v1
kind: Service
metadata:
  name: yolok8s-backend-service
spec:
  selector:
    app: yolok8s-backend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 31000